export { default as Home } from "./Home"
export { default as Navigation } from "./Navigation"
export { default as Minter } from "./Minter"
export { default as CrowdSale } from "./CrowdSale"
export { default as Register } from "./Register"
export { default as Exchange } from "./Exchange"